### ISSUE TITLE
JVM docker image not working

### ISSUE THREAD

**Issue by dcdh** [quarkiverse/quarkus-opencv#155]
Hello

When running a docker container using in JVM the application failed to start.

```
ERROR: Failed to start application (with profile [prod])
java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/opencv_openpnp7808631469231151283/nu/pattern/opencv/linux/x86_64/libopencv_java481.so: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/opencv_openpnp7808631469231151283/nu/pattern/opencv/linux/x86_64/libopencv_java481.so)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
```

Steps to reproduce:

1. git clone https://github.com/dcdh/opencv-sample.git
2. mvn clean install -Dquarkus.container-image.build=true
3. docker run damien/opencv-sample:1.0.0-SNAPSHOT

Additional information:
- Quarkus version 3.8.3
- uname -a : Linux 2a02-8428-dff8-c601-234b-8c10-a3c4-2308.rev.sfr.net 6.6.11-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jan 10 19:25:59 UTC 2024 x86_64 GNU/Linux

Regards,

Damien

**Comment by vaughank** [comment]
Changing back to version 2.0.1 of opencv fixed this for me in the short term...

**Comment by lu1tr0n** [comment]
Hi @dcdh,

The cause here is the base image: the OpenCV library needs glibc 2.29 or newer, and the older UBI 8 image doesn't have it, so it can't load. Switching to a UBI 9 (or Fedora) base image fixes it, I tested it and the app starts fine.

Recent Quarkus versions already use UBI 9 by default. I opened #163 updating the extension and adding a short note about this.

Thanks!
